# Generated by Django 4.1.2 on 2022-12-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='User Telegram ID')),
                ('user_city', models.TextField(verbose_name='city that user have entered')),
                ('first_name', models.TextField(verbose_name='User first_name')),
                ('last_name', models.TextField(verbose_name='User last_name')),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
